### ISSUE TITLE
Implement smart positioning of the popup

### ISSUE THREAD

**Issue by robinwassen** [DigiExam/ng-annotate-text#11]
Implement smart positioning of the popup.

**Background:** If there is not enough space for the popup to be shown on the left side, it will currently be placed outside the screen.

**Expected result:** The popup should check if there is enough room, otherwise look at other placement options in the following order:
- Left
- Right
- Below

**Comment by robinwassen** [comment]
Added a quick and dirty "fix" for this until we have time to do it properly: https://github.com/DigiExam/ng-annotate/commit/e8195e85598fd2c2a33e6ab967d74f96dfd59acf

**Comment by KennethSundqvist** [comment]
Fixed in 2.5.0
